# Set prefixes to Ctrl+b (default) and Ctrl+s
unbind C-s
set -g prefix2 C-s
bind C-s send-prefix

# Easy config reload with r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Faster escape time (important for vim)
set -sg escape-time 0

# Start window numbering at 1
set -g base-index 1

# Increase scrollback size
set-option -g history-limit 50000

# Enable xterm like navigation (Ctrl-Left)
set-window-option -g xterm-keys on

# Enable 256 color support
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"

# Enable Mouse mode
set -g mouse on

# vi like navigation
set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Pane resizing with Shift + vim keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Override default splits to also use current path
bind c new-window -c "#{pane_current_path}"
# Cygwin hack
# bind c run-shell 'DIR=$(tmux display -p "#{pane_current_path}"); tmux new-window \; send-keys "cd \"$DIR\" && clear" Enter'
# dynamic switch for cygwin
# if-shell 'uname -o 2>/dev/null | grep -qi cygwin' \
#   'bind c run-shell "DIR=$(tmux display -p \"#{pane_current_path}\"); tmux new-window \\; send-keys \"cd \\\"$DIR\\\" && clear\" Enter"' \
#   'bind c new-window -c "#{pane_current_path}"'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Split panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
